"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import { ThemeProvider } from "@mui/material/styles";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import theme from "@/lib/theme";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);
  return (
    <html lang="en">
        <Provider store={store}>
          <SessionProvider>
      <body>
      <ThemeProvider theme={theme}>
            {children}
            <Toaster />
      </ThemeProvider>
      </body>
          </SessionProvider>
        </Provider>
    </html>
  );
}
