"use client";
import Home from '@/components/home/Home';
import { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function page() {
 

  return (
    <>
   <Home/>
    </>
  );
};